global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Kong metrics
  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Kuma Control Plane metrics
  - job_name: 'kuma-control-plane'
    static_configs:
      - targets: ['kuma-control-plane:5681']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Future microservices will be added here
  # Example for when we deploy authentication service:
  # - job_name: 'authentication-service'
  #   static_configs:
  #     - targets: ['authentication-service:8080']
  #   metrics_path: '/metrics'
  #   scrape_interval: 15s
