name: Data Services CI/CD Pipeline

on:
  push:
    branches: [main, develop]
    paths:
      - 'apps/backend-services/user-management-service/**'
      - 'apps/backend-services/data-management-service/**'
      - 'apps/backend-services/analytics-service/**'
      - 'infra/k8s/data-services/**'
  pull_request:
    branches: [main]
    paths:
      - 'apps/backend-services/user-management-service/**'
      - 'apps/backend-services/data-management-service/**'
      - 'apps/backend-services/analytics-service/**'
      - 'infra/k8s/data-services/**'

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: 002aic

jobs:
  # Detect which data services changed
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      user-management-service: ${{ steps.changes.outputs.user-management-service }}
      data-management-service: ${{ steps.changes.outputs.data-management-service }}
      analytics-service: ${{ steps.changes.outputs.analytics-service }}
      k8s-manifests: ${{ steps.changes.outputs.k8s-manifests }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          user-management-service:
            - 'apps/backend-services/user-management-service/**'
          data-management-service:
            - 'apps/backend-services/data-management-service/**'
          analytics-service:
            - 'apps/backend-services/analytics-service/**'
          k8s-manifests:
            - 'infra/k8s/data-services/**'

  # Security and compliance scanning
  security-scan:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: |
      needs.detect-changes.outputs.user-management-service == 'true' ||
      needs.detect-changes.outputs.data-management-service == 'true' ||
      needs.detect-changes.outputs.analytics-service == 'true'
    steps:
    - uses: actions/checkout@v4
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'
    
    # Additional security scan for user management service
    - name: GDPR Compliance Check
      if: needs.detect-changes.outputs.user-management-service == 'true'
      run: |
        echo "Running GDPR compliance checks for user management service..."
        # Add specific GDPR compliance validation scripts here
        python scripts/compliance/gdpr_check.py apps/backend-services/user-management-service/

  # Build and test Go data services
  build-go-services:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: |
      needs.detect-changes.outputs.user-management-service == 'true' ||
      needs.detect-changes.outputs.data-management-service == 'true'
    strategy:
      matrix:
        service: [user-management-service, data-management-service]
    steps:
    - uses: actions/checkout@v4
    
    - name: Check if service changed
      id: check-service
      run: |
        if [ "${{ needs.detect-changes.outputs[matrix.service] }}" == "true" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Set up Go
      if: steps.check-service.outputs.changed == 'true'
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Cache Go modules
      if: steps.check-service.outputs.changed == 'true'
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Download dependencies
      if: steps.check-service.outputs.changed == 'true'
      working-directory: ./apps/backend-services/${{ matrix.service }}
      run: go mod download
    
    - name: Run linting
      if: steps.check-service.outputs.changed == 'true'
      working-directory: ./apps/backend-services/${{ matrix.service }}
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        golangci-lint run
    
    - name: Run tests
      if: steps.check-service.outputs.changed == 'true'
      working-directory: ./apps/backend-services/${{ matrix.service }}
      run: go test -v -race -coverprofile=coverage.out ./...
    
    - name: Upload coverage reports
      if: steps.check-service.outputs.changed == 'true'
      uses: codecov/codecov-action@v3
      with:
        file: ./apps/backend-services/${{ matrix.service }}/coverage.out
        flags: ${{ matrix.service }}
    
    - name: Build binary
      if: steps.check-service.outputs.changed == 'true'
      working-directory: ./apps/backend-services/${{ matrix.service }}
      run: |
        CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .
    
    - name: Build Docker image
      if: steps.check-service.outputs.changed == 'true'
      working-directory: ./apps/backend-services/${{ matrix.service }}
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.service }}:${{ github.sha }} .
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.service }}:latest .
    
    - name: Log in to Container Registry
      if: steps.check-service.outputs.changed == 'true' && github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Push Docker image
      if: steps.check-service.outputs.changed == 'true' && github.event_name != 'pull_request'
      run: |
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.service }}:${{ github.sha }}
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.service }}:latest

  # Build and test Python analytics service
  build-python-services:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.analytics-service == 'true'
    strategy:
      matrix:
        service: [analytics-service]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      working-directory: ./apps/backend-services/${{ matrix.service }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov black flake8 mypy pandas numpy
    
    - name: Run linting
      working-directory: ./apps/backend-services/${{ matrix.service }}
      run: |
        black --check .
        flake8 .
        mypy .
    
    - name: Run tests
      working-directory: ./apps/backend-services/${{ matrix.service }}
      run: |
        pytest --cov=. --cov-report=xml --cov-report=term-missing
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./apps/backend-services/${{ matrix.service }}/coverage.xml
        flags: ${{ matrix.service }}
    
    - name: Build Docker image
      working-directory: ./apps/backend-services/${{ matrix.service }}
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.service }}:${{ github.sha }} .
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.service }}:latest .
    
    - name: Log in to Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Push Docker image
      if: github.event_name != 'pull_request'
      run: |
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.service }}:${{ github.sha }}
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.service }}:latest

  # Data-specific integration tests
  data-integration-tests:
    runs-on: ubuntu-latest
    needs: [build-go-services, build-python-services]
    if: always() && (needs.build-go-services.result == 'success' || needs.build-python-services.result == 'success')
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      mongodb:
        image: mongo:7.0
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
        ports:
          - 27017:27017
      elasticsearch:
        image: elasticsearch:8.10.2
        env:
          discovery.type: single-node
          xpack.security.enabled: false
          ES_JAVA_OPTS: -Xms512m -Xmx512m
        ports:
          - 9200:9200
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install test dependencies
      run: |
        pip install pytest requests pymongo elasticsearch pandas
    
    - name: Wait for services to be ready
      run: |
        sleep 30
        curl -f http://localhost:9200/_cluster/health || exit 1
    
    - name: Run data integration tests
      working-directory: ./test/integration
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db?sslmode=disable
        REDIS_URL: redis://localhost:6379
        MONGODB_URL: mongodb://admin:password@localhost:27017/admin
        ELASTICSEARCH_URL: http://localhost:9200
      run: |
        python -m pytest data-services/ -v --tb=short

  # Data quality and compliance tests
  data-quality-tests:
    runs-on: ubuntu-latest
    needs: [build-go-services, build-python-services]
    if: |
      needs.build-go-services.result == 'success' ||
      needs.build-python-services.result == 'success'
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install data quality tools
      run: |
        pip install great-expectations pandas sqlalchemy psycopg2-binary
    
    - name: Run data quality tests
      run: |
        python test/data-quality/run_quality_checks.py
    
    - name: Generate data quality report
      run: |
        python test/data-quality/generate_report.py
    
    - name: Upload data quality artifacts
      uses: actions/upload-artifact@v3
      with:
        name: data-quality-report
        path: test/data-quality/reports/

  # Deploy to staging
  deploy-data-staging:
    runs-on: ubuntu-latest
    needs: [security-scan, build-go-services, build-python-services, data-integration-tests, data-quality-tests]
    if: |
      always() && 
      github.ref == 'refs/heads/develop' &&
      (needs.build-go-services.result == 'success' || needs.build-python-services.result == 'success') &&
      needs.data-integration-tests.result == 'success'
    environment: staging
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.0'
    
    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG_STAGING }}" | base64 -d > kubeconfig
        export KUBECONFIG=kubeconfig
    
    - name: Update image tags in manifests
      run: |
        sed -i "s|002aic/user-management-service:latest|${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/user-management-service:${{ github.sha }}|g" infra/k8s/data-services/user-management-service.yaml
        sed -i "s|002aic/data-management-service:latest|${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/data-management-service:${{ github.sha }}|g" infra/k8s/data-services/data-management-service.yaml
        sed -i "s|002aic/analytics-service:latest|${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/analytics-service:${{ github.sha }}|g" infra/k8s/data-services/analytics-service.yaml
    
    - name: Deploy data services to staging
      run: |
        export KUBECONFIG=kubeconfig
        kubectl apply -f infra/k8s/data-services/ -n aic-data-staging
        kubectl rollout status deployment --all -n aic-data-staging --timeout=600s

  # Deploy to production
  deploy-data-production:
    runs-on: ubuntu-latest
    needs: [security-scan, build-go-services, build-python-services, data-integration-tests, data-quality-tests]
    if: |
      always() && 
      github.ref == 'refs/heads/main' &&
      (needs.build-go-services.result == 'success' || needs.build-python-services.result == 'success') &&
      needs.data-integration-tests.result == 'success' &&
      needs.data-quality-tests.result == 'success'
    environment: production
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.0'
    
    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG_PRODUCTION }}" | base64 -d > kubeconfig
        export KUBECONFIG=kubeconfig
    
    - name: Update image tags in manifests
      run: |
        sed -i "s|002aic/user-management-service:latest|${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/user-management-service:${{ github.sha }}|g" infra/k8s/data-services/user-management-service.yaml
        sed -i "s|002aic/data-management-service:latest|${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/data-management-service:${{ github.sha }}|g" infra/k8s/data-services/data-management-service.yaml
        sed -i "s|002aic/analytics-service:latest|${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/analytics-service:${{ github.sha }}|g" infra/k8s/data-services/analytics-service.yaml
    
    - name: Deploy data services to production
      run: |
        export KUBECONFIG=kubeconfig
        kubectl apply -f infra/k8s/data-services/ -n aic-data
        kubectl rollout status deployment --all -n aic-data --timeout=600s
    
    - name: Run data services smoke tests
      run: |
        export KUBECONFIG=kubeconfig
        # Wait for services to be ready
        sleep 60
        
        # Test data services through API Gateway
        GATEWAY_IP=$(kubectl get service api-gateway-service -n aic-platform -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        
        # Run basic health checks for data services
        curl -f http://$GATEWAY_IP/v1/data/user-management/health || exit 1
        curl -f http://$GATEWAY_IP/v1/data/data-management/health || exit 1
        curl -f http://$GATEWAY_IP/v1/data/analytics/health || exit 1
        
        # Test user management endpoints
        curl -f http://$GATEWAY_IP/v1/users/health || exit 1
        
        # Test data management endpoints
        curl -f http://$GATEWAY_IP/v1/datasets/health || exit 1
        
        # Test analytics endpoints
        curl -f http://$GATEWAY_IP/v1/analytics/health || exit 1

  # Notify on completion
  notify:
    runs-on: ubuntu-latest
    needs: [deploy-data-staging, deploy-data-production]
    if: always()
    steps:
    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        channel: '#data-services-deployments'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        fields: repo,message,commit,author,action,eventName,ref,workflow
